services:
  neuronal-lens-downloader:
    image: registry.gitlab.tugraz.at/hereditary/neuronal-lens:dataset-downloader_master
    build:
      context: .
      dockerfile: Dockerfile.downloader
    volumes:
      - stimulus:/data
    restart: no

  neuronal-lens-frontend:
    image: registry.gitlab.tugraz.at/hereditary/neuronal-lens:frontend_master
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - stimulus:/usr/share/nginx/html/stimulus
    depends_on:
      neuronal-lens-downloader:
        condition: service_completed_successfully
    networks:
      - web
    labels:
      - traefik.http.routers.neuronal-lens-http.rule=Host(`hereditary.cgv.tugraz.at`) && PathPrefix(`/neuronal-lens/`)
      - traefik.http.routers.neuronal-lens-http.entrypoints=http
      - traefik.http.routers.neuronal-lens-https.rule=Host(`hereditary.cgv.tugraz.at`) && PathPrefix(`/neuronal-lens/`)
      - traefik.http.routers.neuronal-lens-https.entrypoints=https
      - traefik.http.routers.neuronal-lens-https.tls=true
      - traefik.http.routers.neuronal-lens-https.tls.certresolver=letsencrypt
      - traefik.http.routers.neuronal-lens-http.middlewares=redirect,neuronal-lens_sp@docker
      - traefik.http.routers.neuronal-lens-https.middlewares=redirect,neuronal-lens_sp@docker
      - traefik.http.middlewares.neuronal-lens_sp.stripprefix.prefixes=/neuronal-lens
      - traefik.http.middlewares.neuronal-lens_sp.stripprefix.forceSlash=false
      - traefik.http.middlewares.redirect.redirectscheme.scheme=https
      - traefik.http.services.neuronal-lens.loadbalancer.server.port=80

networks:
  web:
    external: true

volumes:
  stimulus:
